export const CREATE_LIBRARY = "CREATE_LIBRARY";
export const RETRIEVE_LIBRARIES = "RETRIEVE_LIBRARIES";
export const UPDATE_LIBRARY = "UPDATE_LIBRARY";
export const DELETE_LIBRARY = "DELETE_LIBRARY";
export const DELETE_ALL_LIBRARIES = "DELETE_ALL_LIBRARIES";